import Head from "next/head";

export default function head() {
  return (
    <Head>
      <title>Create Next Appy</title>
      <meta name="description" content="Generated by create next appy" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        property="og:image"
        content="https://lucasamos.dev/static/ad1dd43a1f5b7b097de944e9a5f84494/2a4de/terraform.png"
      />
    </Head>
  );
}
