import Head from "next/head";

export default function head() {
  return (
    <Head>
      <title>Create Next Appy</title>
      <meta name="description" content="Generated by create next appy" />
      <link rel="icon" href="/favicon.ico" />
      <meta property="og:image" content="/jest.png" />

      <meta property="og:title" content="next title" />
    </Head>
  );
}
